train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.ASVSpoofDataset
      asv_root_path: "D:/Downloads"
      asv_protocol_path: "D:/Downloads/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
      access_type: "LA"
      stage: "train"
      instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.ASVSpoofDataset
  asv_root_path: "D:/Downloads"
  asv_protocol_path: "D:/Downloads/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt"
  access_type: "LA"
  stage: "dev"
  instance_transforms: ${transforms.instance_transforms.inference}

test:
  _target_: src.datasets.ASVSpoofDataset
  asv_root_path: "D:/Downloads"
  asv_protocol_path: "D:/Downloads/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"
  access_type: "LA"
  stage: "eval"
  instance_transforms: ${transforms.instance_transforms.inference}
