device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.ExampleMetric
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 2
    device: ${metrics.device}
    name: "TRAIN_MulticlassAccuracy" # just an example to see difference
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.EERMetric
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 2
    device: ${metrics.device}
    name: "MulticlassAccuracy"
