defaults:
  - model: baseline
  - writer: wandb
  - metrics: metrics_list
  - datasets: asvspoof
  - dataloader: loader
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0.02
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.ASoftmax

trainer:
  log_step: 400
  n_epochs: 20
  epoch_len: 700
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  save_period: 2 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: ./out/${now:%Y-%m-%d}/${now:%H-%M-%S}
  seed: 1
